### ISSUE TITLE
I get this error, can you help me pls?

### ISSUE THREAD

**Issue by ultrapromedia** [scttcper/ng2-adsense#78]
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ng2-adsense' is not a known element:
1. If 'ng2-adsense' is an Angular component, then verify that it is part of this module.
2. If 'ng2-adsense' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <div class="col-md-3">

      [ERROR ->]<ng2-adsense></ng2-adsense>

      <div id="col3" class="gr-1 panel">
"): ng:///BachecaModule/BachecaDashboardComponent.html@46:6
Error: Template parse errors:
'ng2-adsense' is not a known element:
1. If 'ng2-adsense' is an Angular component, then verify that it is part of this module.
2. If 'ng2-adsense' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <div class="col-md-3">

      [ERROR ->]<ng2-adsense></ng2-adsense>

      <div id="col3" class="gr-1 panel">
"): ng:///BachecaModule/BachecaDashboardComponent.html@46:6
    at syntaxError (https://scuola365.com/vendor.bundle.js:170612:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (https://scuola365.com/vendor.bundle.js:181724:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (https://scuola365.com/vendor.bundle.js:195770:39)
    at https://scuola365.com/vendor.bundle.js:195690:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (https://scuola365.com/vendor.bundle.js:195690:19)
    at https://scuola365.com/vendor.bundle.js:195577:19
    at Object.then (https://scuola365.com/vendor.bundle.js:170602:148)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (https://scuola365.com/vendor.bundle.js:195576:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (https://scuola365.com/vendor.bundle.js:195505:37)
    at syntaxError (https://scuola365.com/vendor.bundle.js:170612:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (https://scuola365.com/vendor.bundle.js:181724:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (https://scuola365.com/vendor.bundle.js:195770:39)
    at https://scuola365.com/vendor.bundle.js:195690:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (https://scuola365.com/vendor.bundle.js:195690:19)
    at https://scuola365.com/vendor.bundle.js:195577:19
    at Object.then (https://scuola365.com/vendor.bundle.js:170602:148)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (https://scuola365.com/vendor.bundle.js:195576:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (https://scuola365.com/vendor.bundle.js:195505:37)
    at resolvePromise (https://scuola365.com/vendor.bundle.js:156882:31)
    at resolvePromise (https://scuola365.com/vendor.bundle.js:156853:17)
    at https://scuola365.com/vendor.bundle.js:156930:17
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (https://scuola365.com/vendor.bundle.js:156536:31)
    at Object.onInvokeTask (https://scuola365.com/vendor.bundle.js:200576:37)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (https://scuola365.com/vendor.bundle.js:156535:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (https://scuola365.com/vendor.bundle.js:156303:47)
    at drainMicroTaskQueue (https://scuola365.com/vendor.bundle.js:156696:35)
    at <anonymous>

**Comment by scttcper** [comment]
Please show how you're importing it in your ngmodule. https://github.com/scttcper/ng2-adsense#3-add-to-ngmodule

**Comment by ultrapromedia** [comment]
I have import this
import { AdsenseModule } from 'ng2-adsense';

And then i have put:
@NgModule({
    imports: [ BrowserModule,
                RouterModule.forRoot(routes),
                FormsModule,
                ReactiveFormsModule,
                HttpModule,
                DropdownModule.forRoot(),
                CalendarModule.forRoot(),
                ModalModule.forRoot(),
                BootstrapModalModule,
                Ng2DatetimePickerModule,
                SimpleNotificationsModule,
                PushNotificationsModule,
                Ng2AutoCompleteModule,
                AccordionModule,
                CollapseModule,
                Ng2BreadcrumbModule.forRoot(),                
                CommonstuffModule.forRoot(),
                CarouselModule.forRoot(),
                RlTagInputModule,
                AdsenseModule.forRoot({
                  adClient: 'ca-pub-8954455297155966',
                  adSlot: 3659265737
                  }),
              ],

And then in my html i have:

<ng2-adsense
        [adClient]="'ca-pub-7640562161899788'"
        [adSlot]="7259870550"
        [display]="'inline-block'"
        [width]="320"
        [height]="108">
      </ng2-adsense>

**Comment by scttcper** [comment]
Make sure you have AdsenseModule imported in any sub modules as well.

**Comment by VanDxtr** [comment]
I have imported also in all my module this:

import { AdsenseModule } from 'ng2-adsense';

and i have this:  :((  :(( 

ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ng2-adsense' is not a known element:
1. If 'ng2-adsense' is an Angular component, then verify that it is part of this module.
2. If 'ng2-adsense' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <div class="col-md-3">

      [ERROR ->]<ng2-adsense></ng2-adsense>

      <div id="col3" class="gr-1 panel">
"): ng:///BachecaModule/BachecaDashboardComponent.html@46:6
Error: Template parse errors:
'ng2-adsense' is not a known element:
1. If 'ng2-adsense' is an Angular component, then verify that it is part of this module.
2. If 'ng2-adsense' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <div class="col-md-3">

      [ERROR ->]<ng2-adsense></ng2-adsense>

      <div id="col3" class="gr-1 panel">
"): ng:///BachecaModule/BachecaDashboardComponent.html@46:6
    at syntaxError (http://localhost/vendor.bundle.js:170724:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost/vendor.bundle.js:181836:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost/vendor.bundle.js:195882:39)
    at http://localhost/vendor.bundle.js:195802:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost/vendor.bundle.js:195802:19)
    at http://localhost/vendor.bundle.js:195689:19
    at Object.then (http://localhost/vendor.bundle.js:170714:148)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost/vendor.bundle.js:195688:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost/vendor.bundle.js:195617:37)
    at syntaxError (http://localhost/vendor.bundle.js:170724:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost/vendor.bundle.js:181836:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost/vendor.bundle.js:195882:39)
    at http://localhost/vendor.bundle.js:195802:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost/vendor.bundle.js:195802:19)
    at http://localhost/vendor.bundle.js:195689:19
    at Object.then (http://localhost/vendor.bundle.js:170714:148)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost/vendor.bundle.js:195688:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost/vendor.bundle.js:195617:37)
    at resolvePromise (http://localhost/vendor.bundle.js:157000:31)
    at resolvePromise (http://localhost/vendor.bundle.js:156971:17)
    at http://localhost/vendor.bundle.js:157048:17
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost/vendor.bundle.js:156654:31)
    at Object.onInvokeTask (http://localhost/vendor.bundle.js:200688:37)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost/vendor.bundle.js:156653:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost/vendor.bundle.js:156421:47)
    at drainMicroTaskQueue (http://localhost/vendor.bundle.js:156814:35)
    at HTMLAnchorElement.ZoneTask.invoke (http://localhost/vendor.bundle.js:156720:25)

**Comment by scttcper** [comment]
Maybe delete your node_modules folder and reinstall everything. Is the project open source anywhere?

**Comment by ultrapromedia** [comment]
Yes, and i have delete and reinstall everything...but Nothing..the same error

**Comment by msahil432** [comment]
I am having the same error, How to resolve it?
I have added this statement to every .ts module, file, everything!
import { AdsenseModule } from 'ng2-adsense';

This statement to app.module.ts, 
AdsenseModule.forRoot({
          adClient: '',
          adSlot: ,
        })

I have tried ng-adsense and ng2-adsense both tags.
I have reinstalled all node-modules, but still nothing!

Please help me.
